/* Automatically generated by configure - do not modify! */
#ifndef FFMPEG_CONFIG_H
#define FFMPEG_CONFIG_H
#define FFPLAY 0
#define CONFIG_AVFILTER 0
#define DEBUG 1
#define CONFIG_RTSP_DEMUXER 0
#define CONFIG_MMSH_PROTOCOL 0
#define CONFIG_AVDEVICE 0
#define CONFIG_THREAD_PTHREAD_RECURSIVE_MUTEX 0
#define CONFIG_THREAD_PTHREAD_RECURSIVE_MUTEX_NP 0
#define FAKE_RECURSIVE_MUTEX 0
#define CONFIG_AVUTIL 1
#define FFMPEG_CONFIGURATION "--target-os=linux --arch=armv6 --enable-cross-compile --cc=/usr/local/android-ndk-r7/toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/arm-linux-androideabi-gcc --cross-prefix=/usr/local/android-ndk-r7/toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/arm-linux-androideabi- --nm=/usr/local/android-ndk-r7/toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/arm-linux-androideabi-nm --extra-cflags='-fPIC -DANDROID' --enable-shared --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-ffserver --disable-avfilter --enable-small --enable-armv6 --enable-armv6t2 --enable-armvfp --enable-pic --disable-encoders --enable-asm --enable-yasm --prefix=/home/ffmpeg-android-bin --extra-ldflags='-Wl,-T,/usr/local/android-ndk-r7/toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/arm-linux-androideabi/lib/ldscripts/armelf_linux_eabi.x -Wl,-rpath-link=/usr/local/android-ndk-r7/platforms/android-4/arch-arm/usr/lib -L/usr/local/android-ndk-r7/platforms/android-4/arch-arm/usr/lib -nostdlib /usr/local/android-ndk-r7/toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.4.3/crtbegin.o /usr/local/android-ndk-r7/toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.4.3/crtend.o -lc -lm -ldl'"
#define CONFIG_AVCODEC 1
#define CONFIG_AVFORMAT 1
#define CONFIG_SWSCALE 1
#define CONFIG_SWRESAMPLE 1
#define CC_TYPE "gcc"
#define CC_VERSION __VERSION__
#define FFMPEG_DATADIR "/home/ffmpeg-android-bin/share/ffmpeg"
#define xxxxxxxxxxxxxxxxxxxxx 0
#define xxxxxxxxxxxxxxxxxxxxx 0
#define xxxxxxxxxxxxxxxxxxxxx 0
#define xxxxxxxxxxxxxxxxxxxxx 0
#define xxxxxxxxxxxxxxxxxxxxx 0
#define xxxxxxxxxxxxxxxxxxxxx 0
#define xxxxxxxxxxxxxxxxxxxxx 0
#define xxxxxxxxxxxxxxxxxxxxx 0
#endif /* FFMPEG_CONFIG_H */
